/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ls_ndkcallback_DataCallback */

#ifndef _Included_com_ls_ndkcallback_DataCallback
#define _Included_com_ls_ndkcallback_DataCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ls_ndkcallback_DataCallback
 * Method:    method1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ls_ndkcallback_DataCallback_method1
  (JNIEnv *, jobject);

/*
 * Class:     com_ls_ndkcallback_DataCallback
 * Method:    method2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ls_ndkcallback_DataCallback_method2
  (JNIEnv *, jobject);

/*
 * Class:     com_ls_ndkcallback_DataCallback
 * Method:    method3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ls_ndkcallback_DataCallback_method3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
